### ISSUE TITLE
include A tag in description

### ISSUE THREAD

**Issue by giangnth** [daxslab/web2py-simple-seo#1]
I want to add raw A tag in description meta.
Example: <meta name="description" content="A <a href='http://example.com'>A Tag</a>" />
But when i try to add, meta tag return: <meta name="description" content="A <a href='http://example.com'>A Tag&lt;/a&gt;" />
How to do that?
sorry for my bad english !

**Comment by cccaballero** [comment]
@giangnth Meta descriptions can not contain raw tags, search engines will ignore them or show them as raw strings, if you want links in the google search result, you can look at [sitelinks](https://support.google.com/webmasters/answer/47334?hl=en)
